export const strings = {
    PARA_1: `Your mother also gave me a tour of the home and its history. It's even more sumptuous in the light of the day, nearly an assault on the senses. Even with the peeling paint and grass growing on the overhangs , it's clear how much she loves it.`,
    PARA_2: `She told me it's been in the family for almost over a hundred years now, built by her textile merchant grandfather. At one point, the “five-foot-way” was a continuous overhanging canopy that connected with your neighbors', and was where he ran his business. The house is so long and narrow, that without the skywell that pierces its core, the interior would be otherwise devoid of sunlight. Rain water and leaf litter from last night has collected in the little pool in its center.`,
    PARA_3: `Her eyes sparkled as she took me from room to room, pointing out the Malay timber fretwork and French windows, the Portuguese shutters and Corinthian pilasters, the Chinese porcelain-chip friezes on the facade. Which was your favorite part? The flight of bats, the herons flapping their wings, the leopard stalking its prey?`,
    PARA_4: `I pass by walls covered in patterned wallpaper, paintings, and family photographs. The floors are clad in chipped peranakan clay tiles and moldering rugs. I'm surrounded by ornately carved antiques in mahogany, teak, and ebony that must have been in your family for generations. The house feels like a rock that your family is clinging to, amidst the sea of progress just outside.`,
    PARA_5: `It's almost comical thinking that you - Lawrence Chen - man who is comfortable subsisting on instant ramen and sleeping on a mattress on the floor of your apartment, grew up  here.  Still, I feel like I understand you better, just being here, imagining you as a child bounding through these corridors. There's something of your old-world ways in these walls.`,
    PARA_6: `There was one strange thing, though. A locked door on the third floor caught my eye. It stood out simply because the red paint looked so fresh, and nothing else in the house looked nearly so recently maintained. When I asked your mother about it, she stammered at first, and then told me it just lead to the attic. Then, she started telling me about all the old linens and family heirlooms stored up there, without being asked. Almost as if …no, it's probably nothing. I just smiled and changed the subject, and she seemed grateful. I hope I didn't come off too awkwardly`,
    PARA_7: `More tomorrow, night Lawrence.`,
}
