export const strings = {
    DATE: `October 13, 1991`,
    PARA_1: `I woke up this morning and the door is locked. They have trapped me here.`,
    PARA_2: `I pounded on the door, and screamed and cried. No one is coming to get me. What is happening? How could they do this? What did I do wrong?`,
    PARA_3: `And then it becomes sickenly obvious why they asked me to come here to begin with.`,
    PARA_4: `I am the key ingredient of the sick ritual they are concocting. And this knowledge that nobody wants me tears me apart. I wet myself, as I'm tied up in the paper maquette your mother has made for me. She sets it alight, and even my own urine will not stop the flames licking up the paper. I start to burn, I scream.`,
    PARA_5: `Oh god.`,
    PARA_6: `These people are going to kill me.  I'm trapped here. Help me Lawrence, please help me. I'm so sorry. I'm so sorry. I'm so sorry. I'm so sorry. I'm so sorry. I'm so sorry. These people are going to kill me. These people are going to kill me. Please let me out. Help me Lawrence, these people are going to kill me. They are going to kill me. These people are going to kill me. I know it, I just know it. They are going to kill me. They are going to kill me. These people are going to kill -`,
    PARA_7: `And then the miracle happens. I hear a subtle click open of the door, and it swings open freely on its own open to the dark.`,
    PARA_8: `I can't believe what is happening.`,
    PARA_9: `You step through the doorway, smiling at me with your soft eyes.`,
    PARA_10: `You take me in your arms.`,
    PARA_11: `I am a mess of tears as I kiss you.`,
    PARA_12: `I'm so sorry.`,
    PARA_13: `I'm so sorry.`,
    PARA_14: `I'm so sorry.`,
    PARA_15: `I know you want me to let it go. I know you have come here to set me free.`,
    PARA_16: `I want to come with you. But first they're going to regret what they tried to do. I am Vanessa Wong. I have been someone else's pawn my whole life. Nobody really wanted me. But they will miss me when I am gone. They were fools not to see it, and they are going to regret it.`,
    PARA_17: `I will set their ignorance alight. Their blindness will fly and melt into the dark air, like the ashes of a paper doll.`,
    PARA_18: `I am the last tiger of Singapore.`,
    PARA_19: `They will all see how bright I burn.`,
}
