export const strings = {
    DATE: `August 24, 1991`,
    PARA_1: `Had dinner with your family today. I leave for London the day after next, so your family wanted to give me a proper send off. The scent of something spicy and mouth-watering has been drifting through the house all afternoon. Hwee prepared braised duck, spicy peanut snow pea shoots, fried fish, and an indescribable fried rice dish I must ask your mother about.`,
    PARA_2: `It was a rare evening to have your father home from business abroad. Mr. Chen asked me about my family and how I grew up. I managed some limp answers, but I can't remember them now. How could I have possibly told him the truth?`,
    PARA_3: `When my brother was born, my father celebrated. When I was born, well,  my father started to bide his time till he could have my brother. Could I tell them that we were a poor family that grew up pretending to be a rich one? About the constant stream of bills marked “URGENT” and “FINAL NOTICE” in red on the envelopes? About how they would brag about my academics to friends and relatives in public, and in private, take everything out on me? `,
    PARA_4: `What about the time I came home with less than satisfactory results from my A-levels, and my father screamed at me for an hour over family dinner? I remember how something rose up in me, from where I don't know, and I yelled back at him. He stood up, arm raised above his head. Sparing my cheek, the back of his hand accidentally struck the glass chandelier over our dining table. It hit with such force, the glass shade dislodged from its sconce and shattered on our kitchen floor. A  door slam later and my father was gone. My mother retreated into the living room. My brother kept his head down and ate. I was left to pick up the literal pieces.`,
    PARA_5: `None of this escaped me, of course. In this house, nothing hits the crystal chandelier over their dining table except the sounds of lively chatter and peals of laughter.`,
    PARA_6: `After dinner, your family and I gathered to watch some silly program on the television, though I think you might have liked it. Even I laughed, despite myself. A genuine laugh, the first one in months! I see the same heartbreak in their eyes as I see in my own when I look in the mirror. And yet, it is a grief that only breeds more warmth between them. A warmth that they freely extend to me, in exchange… for nothing.`,
    PARA_7: `What's wrong with me Lawrence? It is beautiful here. Your family has been nothing but kind and supportive. So why do I still feel so small?`,
}
